name = "openapi-do"
# route = { pattern = "*/*", zone_name = "templates.do" }
main = "./dist/index.mjs"
usage_model = "unbound"
compatibility_date = "2022-09-23"
logpush = true

services = [
  { binding = "CTX", service = "ctx-do", environment = "production" }
]

workers_dev = false

[durable_objects]
bindings = [
  { name = "StorageDurable", class_name = "StorageDurable"},
]

[[migrations]]
tag = "v1" # Should be unique for each entry
new_classes = ["StorageDurable"]


[build]
command = "npm run build"
 
[build.upload]
format = "modules"


[miniflare]
env_path = ".env"
kv_persist = "./data/"

[miniflare.mounts]
ctx-do = "../ctx.do"